local_costmap:
  global_frame: spot3/odom
  robot_base_frame: spot3/base_footprint
  update_frequency: 5.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  track_unknown_space: true
  unknown_cost_value: -1
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
  obstacle_layer:
    observation_sources: laser_scan_sensor 
    laser_scan_sensor: {sensor_frame: spot3/velodyne, data_type: LaserScan, topic: scan, marking: true, clearing: true}
    #lidar_sensor: {sensor_frame: spot2/velodyne, data_type: PointCloud2, topic: lidar_points, marking: true, clearing: true}
  #plugins:
      #- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer", output: "screen"}
