local_costmap:
  global_frame: spot/odom
  robot_base_frame: spot/base_footprint
  update_frequency: 5.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  track_unknown_space: true
  unknown_cost_value: -1
  #plugins:
      #- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer", output: "screen"}
