#goal definition

# Boundary for exploration task
#geometry_msgs/PolygonStamped boundary
# Starting point for exploration task, inside the boundary
bool replan
int32 num_agent
int32 fail_idx
---
#result definition
nav_msgs/Path[] paths
float32 cur_entropy
---
#feedback
#float32 cur_entropy
