#  最大並進速度
base_max_linear_velocity: 0.2
#  最大旋回速度
base_max_angular_velocity: 0.8
#  最大並進加速度
base_max_linear_acceleration: 0.5
#  最大旋回加速度
base_max_angular_acceleration: 1.0
#  ゴール付近並進減速度
base_linear_deceleration_near_goal: 0.5
#  ゴール減速時の並進速度マージン
base_linear_velocity_margin: 0.02
#  経路補間で二点間の補間点数
interpolation_number: 10
#  ゴールエリア判定距離
goal_area_length: 0.5
#  ゴール判定用ラインのゴールからの距離
goal_line_length: 0.05
#  ゴール判定用の位置偏差閾値
goal_stop_error_length: 0.01
#  ゴール判定用の角度偏差閾値
goal_stop_error_angle: 0.01
#  上体の向け方を変えるゴールまでの経路長閾値
path_length_threshold: 1.0
#  並進速度P制御ゲインパラメータ
linear_p_gain: 0.6
#  回転速度P制御ゲインパラメータ
angular_p_gain: 1.0
#  ゴール姿勢合わせゲインパラメータ
goal_angle_gain: 0.6
