waypoints:
    ref_frame: "map"
    locations: ["door", "left_b", "left_t","center_b", "center_t", "right_b", "right_t", "upper_o", "lower_o", "left_o", "right_o", "lupper_o"]
    door: [10.2, 10.9]
    left_b: [6.3, 10.4]
    left_t: [4.7, 5.1]
    center_b: [1.2, 7.0]
    center_t: [-3.8, 7.1]
    right_b: [-8.2, 7.8]
    right_t: [3.8, -2.5]
    upper_o: [0.3, 10.9]
    lower_o: [-8.4, 11.2]
    left_o: [-10.2, 13.6]
    right_o: [-2.8, 13.6]
    lupper_o: [7.6, 13.5]
