#!/usr/bin/env python
import roslib
import rospy
import actionlib
import roslib
import math
import sys
import rospy
import geometry_msgs.msg
from std_msgs.msg import String
from std_msgs.msg import Int8
from nav_msgs.msg import Odometry
import geometry_msgs.msg 
from geometry_msgs.msg import PoseStamped, Point, Quaternion, PoseWithCovarianceStamped
import tf.transformations
import tf
import tf2_ros
import tf_conversions


class tf_converter2(object):
    def __init__(self, wait=0.0):
        # self.cli.wait_for_server()
        self.waypoints=[]
        pose_topic='global_pose_a1_121'
        rospy.Subscriber(pose_topic,PoseStamped, self.robot_pose_Cb)
        initpose_topic='initialpose_a1_121'
        rospy.Subscriber(initpose_topic,PoseWithCovarianceStamped, self.init_pose_Cb)
        self.br= tf2_ros.TransformBroadcaster()
        self.br2= tf2_ros.TransformBroadcaster()
        self.br3= tf2_ros.StaticTransformBroadcaster()
        self.gpose=PoseStamped()
        self.gpose.pose.orientation.w=1.0
        self.initpose=PoseWithCovarianceStamped()
        # self.initpose.pose.pose.orientation.w=1.0
        # self.t = geometry_msgs.msg.TransformStamped()
        # self.t.header.frame_id = "map"
        # self.t.child_frame_id = "base"
        # self.br= tf2_ros.TransformBroadcaster()
    def publish_tf(self):
        t = geometry_msgs.msg.TransformStamped()
        t.header.stamp = rospy.Time.now()
        t.header.frame_id = "map"
        t.child_frame_id = "base"
        # t.header.stamp = self.gpose.header.stamp
        # t.header.stamp = rospy.Time(0)
        # t.header.stamp = self.gpose.header.stamp
        t.transform.translation.x = self.gpose.pose.position.x
        t.transform.translation.y = self.gpose.pose.position.y
        t.transform.translation.z = 0.0
        t.transform.rotation = self.gpose.pose.orientation
        self.br.sendTransform(t)
 
    def publish_tf_velodyne(self):
        # self.br= tf2_ros.TransformBroadcaster()
        t = geometry_msgs.msg.TransformStamped()
        t.header.stamp = rospy.Time.now()
        t.header.frame_id = "map"
        t.child_frame_id = "velodyne"
        # t.header.stamp = self.gpose.header.stamp
        # t.header.stamp = rospy.Time(0)
        # t.header.stamp = self.gpose.header.stamp
        t.transform.translation.x = self.gpose.pose.position.x
        t.transform.translation.y = self.gpose.pose.position.y
        t.transform.translation.z = 0.0
        t.transform.rotation = self.gpose.pose.orientation
        self.br.sendTransform(t)
        # print(self.t.header.stamp)
        # print("transform")
    def publish_tf_init(self):
        t = geometry_msgs.msg.TransformStamped()
        t.header.stamp = rospy.Time.now()
        t.header.frame_id = "map_en"
        t.child_frame_id = "odom"
        # print(self.initpose, "self.initpose")
        t.transform.translation.x = self.initpose.pose.pose.position.x
        t.transform.translation.y = self.initpose.pose.pose.position.y
        t.transform.translation.z = 0.0
        # self.initpose.pose.orientation.w=1.0
        # t.transform.rotation = self.initpose.pose.pose.orientation
        t.transform.rotation.w=1.0
        self.br2.sendTransform(t)
    def publish_tf_map(self):
        t = geometry_msgs.msg.TransformStamped()
        t.header.stamp = rospy.Time.now()
        t.header.frame_id = "map"
        t.child_frame_id = "map_en"
        t.transform.translation.x = -17.5
        t.transform.translation.y = -31.6
        t.transform.translation.z = 0.0
        # self.initpose.pose.orientation.w=1.0
        # t.transform.rotation.z=-0.7068252 
        # t.transform.rotation.w=0.7073252 
        t.transform.rotation.x=0.0
        t.transform.rotation.y=0.0
        t.transform.rotation.z=0.0
        t.transform.rotation.w=1.0
        self.br3.sendTransform(t)


    def robot_pose_Cb(self, msg):
        # rospy.loginfo("call back")
        self.gpose=msg

    def init_pose_Cb(self, msg):
        # rospy.loginfo("call back")
        # br= tf2_ros.TransformBroadcaster()
        self.initpose=msg
  
            
    def starter(self,wait=0.0):
        # make sure the cont0roller is running
        r=rospy.Rate(3000)
        # rospy.spin()            
        while not rospy.is_shutdown():
            self.publish_tf()
            self.publish_tf_map()
            r.sleep()
        # fill ROS message
          
if __name__ == '__main__':
    rospy.init_node('map_tf')
    tf_manager = tf_converter2()
    tf_manager.starter()
    # rospy.spin()



















