#!/usr/bin/python
# -*- coding: utf-8 -*-
import rospy
import sys
import tf
import actionlib
import geometry_msgs.msg
from search_service.msg import *


def mains(srv_name):
    # Initialize
    client = actionlib.SimpleActionClient(str(srv_name),search_service.msg.PathFollowAction)
    client.wait_for_server()
    goal = search_service.msg.PathFollowGoal()
    #goal.start=True
    print("call search action client")
    rospy.loginfo("start action")
    client.send_goal(goal)
    client.wait_for_result()
        
if __name__ == '__main__':
    rospy.init_node('pathfollow_action_client')
    print("arg1: ", sys.argv[1])
    mains(sys.argv[1])

