global_frame: map
robot_base_frame: base_footprint
update_frequency: 5.0
publish_frequency: 2.5
static_map: true
#height: 70
#width: 70
#rolling_window: true
#publish_voxel_map: true
obstacle_range: 2.5
raytrace_range: 5.0
footprint: [[-0.3, -0.3], [0.3, -0.3], [0.3, 0.3], [-0.3, 0.3]]
#inflation_radius: 0.55
#track_unknown_space: true
#static:
    #enable: true
    #map_topic: map

obstalces_laser:
    enable: true
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {data_type: LaserScan, topic: hsrb/base_scan, sensor_frame: base_range_sensor_link, expected_update_rate: 0.4,
    observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
