global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  static_map: true
  width: 60
  height: 60
  track_unknown_space: false
  plugins:
      - {name: static, type: "costmap_2d::StaticLayer"}
      - {name: obstacles_laser, type: "costmap_2d::VoxelLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}
  #map_topic: map

