 global_frame: odom
 robot_base_frame: base_footprint
 update_frequency: 5.0
 publish_frequency: 3.0
 static_map: false
 rolling_window: true
 width: 5.0
 height: 5.0
 resolution: 0.05
 track_unknown_space: true
 unknown_cost_value: -1
 plugins:
   - {name: obstacles_layer, type: "costmap_2d::VoxelLayer"}
   #- {name: inflation, type: "costmap_2d::InflationLayer"}
 obstacles_layer:
     observation_sources: laser_scan_sensor 
     laser_scan_sensor: {sensor_frame: base_range_sensor_link, data_type: LaserScan, topic: hsrb/base_scan, marking: true, clearing: true}
  #plugins:
      #- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer", output: "screen"}
